### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by jwcrawley** [hardillb/node-red-contrib-ldap#1]
The requirements call for LDAP npm module. The project name is now ldap-client as NPM no longer accepts capital letter projects.

Thank you

**Comment by hardillb** [comment]
Can you post the error message?

It should still work as is since it's pinned to a version.

I should really redo it to use one of the pure Node.JS ldap clients  like ldapjs so it will work everywhere and not just systems with openldap libraries.

**Comment by hardillb** [comment]
I've don the update to ldapjs so I'm going to close this. If you still have issues please open a new issue
