### ISSUE TITLE
node-red-node-ldap throws uncaught exception every 3-4 mins

### ISSUE THREAD

**Issue by roemel** [hardillb/node-red-contrib-ldap#2]
> [red] Uncaught Exception:
> Error: read ECONNRESET at
> exports._errnoException (util.js:1018:11)
> at TCP.onread (net.js:572:26)

I'm getting the exception above every 3-4 minutes and then I have to reconnect node-red from command line. The exception doesn't happen anymore when I remove node-red-node-ldap from my nodes. Is there a fix for this or how/where can I handle this exception?
OS: Windows 10

**Comment by hardillb** [comment]
LDAP connections are supposed to be persistent so the question is why your LDAP server is resetting the connection?

I'll try and have a look at the ldapjs library and see if there is a way to catch this, but fixing the LDAP server is a correct way forward

**Comment by roemel** [comment]
I talked to the admin of the LDAP server. He couldn't figure it out yet, but he'll keep looking so we can fix the server. Have you any results if there's a way to catch the exception?

**Comment by hardillb** [comment]
I've managed to have a quick look, but I can't see anything obvious in the ldapjs doc.

You could try adding the following at about line 85 in 99-ldap.js

```
node.ldap.on('error',function(err){
     console.log("foo");
});
``` 

If it prints foo and doesn't crash then I may be able to add some reconnect logic.

**Comment by roemel** [comment]
Oh nice, it didn't crash. It just printed foo. A reconnect logic would be great. Can you please keep me updated when you've added something? Thanks for the help.

**Comment by hardillb** [comment]
install the head version from git (npm install hardillb/node-red-contrib-ldap) and see if that works

**Comment by roemel** [comment]
Now it logs "Error: This socket is closed" (more than 100 times) and then completely shuts down node-red instead of reconnecting.

**Comment by hardillb** [comment]
Is that the whole error message or is it prefixed with "LDAP Connection Error:"?

**Comment by hardillb** [comment]
if so, try removing line 90 (the unbind line) and see what happens

**Comment by roemel** [comment]
Yes this is the whole error message. I'll try remove it after the weekend when I'm back at work. Thx!

**Comment by roemel** [comment]
Oh sorry, I just see that the message is prefixed with "LDAP Connection Error:" as you asked. We're experiencing some network problems right now and the LDAP server isn't working properly. I'll tell you when we fixed everything.

**Comment by roemel** [comment]
Ok the LDAP server is running again. I removed `node.ldap.unbind();` and now I get this error message: "LDAP Connection Error: Error: read ECONNRESET". It doesn't crash in command line, but it doesn't work properly.

For example: We have a login page which checks the credentials the user types in and compares them with LDAP users. If the credentials are correct, it continues, if they're wrong, it shows a simple message that the credentials are wrong.

After the error message above it always tells that the credentials are wrong (even if they're right).

**Comment by hardillb** [comment]
yes, but does it reconnect after 2 seconds?

**Comment by roemel** [comment]
Please have a look at my edit above.

**Comment by hardillb** [comment]
That doesn't make sense, how are you doing authentication? The node is only for doing searches. A bind only happens once at connection (using the credentials supplied in the LDAP Server settings dialog) and you shouldn't be able to retrieve the password as part of a query (and it should be hashed).

Also the node only outputs a message if there are matching results or an empty search is returned by the LDAP server. Have you checked the LDAP logs to see what queries are coming in after the disconnect?

And did you work out why the LDAP server is disconnecting the client?

**Comment by roemel** [comment]
You're right. I guess there's one other problem. We wrote a node for ourself to achieve this login functionality. I guess there's also an error happening.

As we had network problems before, we restarted the server. Now it disconnects every 15min, instead of every 3min. So the tests will take longer now.

I haven't asked the LDAP server admin yet if he could figure out something.

**Comment by roemel** [comment]
Okay it's working now. I just added your reconnect functionality to the node we wrote. Thanks for your help.
